const $=id=>document.getElementById(id), worker=new Worker('inference-worker.js');
let seq=0, pending=new Map(), loaded=false, busy=false, stream=null, source=null, generation=0, last=null, model='lite', changing=false;
const frame=document.createElement('canvas'), ctx=frame.getContext('2d',{willReadFrequently:true}), inference=document.createElement('canvas'), ic=inference.getContext('2d',{willReadFrequently:true}), result=$('result'), rc=result.getContext('2d');
function rpc(message,transfer=[]){return new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});worker.postMessage({...message,id},transfer);});}
worker.onmessage=({data})=>{const p=pending.get(data.id);if(!p)return;pending.delete(data.id);data.error?p.reject(Error(data.error)):p.resolve(data);};
worker.onerror=e=>{for(const p of pending.values())p.reject(Error(e.message));pending.clear();loaded=false;controls();status('推論エンジンを起動できません。ページを再読み込みしてください。',true);};
function status(t,error=false){$('status').textContent=t;$('status').style.color=error?'#ad4039':'';}
function controls(){ $('camera').disabled=!loaded||changing||!!stream; $('file').disabled=!loaded||changing; $('stop').disabled=!stream; $('model').disabled=busy||changing; $('quality').disabled=model==='original'||busy||changing; }
function stop(){generation++;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;$('video').srcObject=null;controls();$('badge').textContent=loaded?'準備完了':'準備中';}
function clear(){last=null;$('count').textContent='—';$('peak').textContent='—';$('speed').textContent='—';$('regions').replaceChildren();$('save').disabled=true;result.hidden=true;$('empty').hidden=false;}
async function load(){if(busy||changing)return;changing=true;stop();clear();loaded=false;model=$('model').value;controls();$('threshold').value=model==='lite'?80:50;$('thresholdText').textContent=$('threshold').value+'%';$('modelNote').textContent=model==='lite'?'細かな傷を補正する軽量モデル':'元モデルと同じ重み。二値化前の確率を表示';status('ONNXモデルを読み込んでいます…');try{await rpc({type:'load',model});loaded=true;$('badge').textContent='準備完了';status('カメラを開始するか、画像を選択してください。');}catch(e){status('モデル読込失敗：'+e.message+'。HTTPサーバーから開いてください。',true);}finally{changing=false;controls();}if(loaded&&source)run(source,generation);}
function regions(data,w,h,threshold){const seen=new Uint8Array(data.length),queue=new Int32Array(data.length),out=[];for(let i=0;i<data.length;i++){if(seen[i]||data[i]<=threshold)continue;let head=0,tail=1;queue[0]=i;seen[i]=1;let x0=w,y0=h,x1=0,y1=0,sum=0,max=0;while(head<tail){const k=queue[head++],x=k%w,y=(k/w)|0;x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);sum+=data[k];max=Math.max(max,data[k]);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const nx=x+dx,ny=y+dy,j=ny*w+nx;if(nx>=0&&nx<w&&ny>=0&&ny<h&&!seen[j]&&data[j]>threshold){seen[j]=1;queue[tail++]=j;}}}if(tail>=3)out.push({x0,y0,x1,y1,mean:sum/tail,max,size:tail,pixels:queue.slice(0,tail)});}return out.sort((a,b)=>b.mean-a.mean);}
function paint(){if(!last)return;const {prediction:p,ms}=last;result.width=frame.width;result.height=frame.height;rc.drawImage(frame,0,0);const list=regions(p.data,p.width,p.height,Number($('threshold').value)/100),sx=result.width/p.width,sy=result.height/p.height;
 if($('mask').checked){const mask=document.createElement('canvas');mask.width=p.width;mask.height=p.height;const mc=mask.getContext('2d'),im=mc.createImageData(p.width,p.height);for(const region of list)for(const k of region.pixels){im.data[k*4]=255;im.data[k*4+1]=95;im.data[k*4+2]=61;im.data[k*4+3]=125;}mc.putImageData(im,0,0);rc.imageSmoothingEnabled=false;rc.drawImage(mask,0,0,result.width,result.height);}
 const fs=Math.max(12,Math.round(result.width/42));rc.font=`600 ${fs}px sans-serif`;rc.lineWidth=Math.max(1.5,result.width/500);list.forEach((r,i)=>{const x=r.x0*sx,y=r.y0*sy;rc.strokeStyle='#ffb65f';rc.strokeRect(x,y,(r.x1-r.x0+1)*sx,(r.y1-r.y0+1)*sy);const label=`${i+1}  ${(r.mean*100).toFixed(1)}%`,tw=rc.measureText(label).width+10,lx=Math.min(x,Math.max(0,result.width-tw)),ly=Math.min(result.height-fs-8,Math.max(0,y-fs-8));rc.fillStyle='#173b35';rc.fillRect(lx,ly,tw,fs+8);rc.fillStyle='white';rc.fillText(label,lx+5,ly+fs+1);});
 $('count').textContent=`${list.length} 領域`;$('peak').textContent=list.length?(list.reduce((m,r)=>Math.max(m,r.max),0)*100).toFixed(1)+'%':'—';$('speed').textContent=`${Math.round(ms)} ms`;$('dimensions').textContent=`推論入力 ${inference.width}×${inference.height} / 確率マップ ${p.width}×${p.height}${stream?' / 最大 '+(1000/(ms+80)).toFixed(1)+' 更新/秒':''}`;$('regions').replaceChildren(...list.slice(0,100).map(r=>{const li=document.createElement('li');li.textContent=`平均 ${(r.mean*100).toFixed(1)}% · 最大 ${(r.max*100).toFixed(1)}% · ${r.size}画素`;return li;}));$('save').disabled=false;result.hidden=false;$('empty').hidden=true;$('badge').textContent=list.length?'傷の候補を検知':'しきい値以上の傷なし';}
async function run(input,token){if(!loaded||busy||changing)return;busy=true;controls();try{let w=input.videoWidth||input.width,h=input.videoHeight||input.height;if(!w||!h)throw Error('画像サイズを読み取れません。');if(model==='original'){w=505;h=256;}else{const scale=Math.min(1,Number($('quality').value)/Math.max(w,h));w=Math.max(8,Math.round(w*scale));h=Math.max(8,Math.round(h*scale));}const ow=input.videoWidth||input.width,oh=input.videoHeight||input.height,ds=Math.min(1,1280/Math.max(ow,oh));frame.width=model==='original'?Math.round(ow*ds):w;frame.height=model==='original'?Math.round(oh*ds):h;ctx.drawImage(input,0,0,frame.width,frame.height);inference.width=w;inference.height=h;ic.drawImage(input,0,0,w,h);const pixels=ic.getImageData(0,0,w,h).data,n=w*h,data=new Float32Array(n*3);for(let i=0;i<n;i++){data[i]=pixels[i*4]/255;data[n+i]=pixels[i*4+1]/255;data[n*2+i]=pixels[i*4+2]/255;}const start=performance.now(),prediction=await rpc({type:'infer',data,width:w,height:h},[data.buffer]);if(token!==generation)return;last={prediction,ms:performance.now()-start};paint();status(stream?'リアルタイム検知中。映像と確率は同じフレームの結果です。':'検知が完了しました。しきい値を動かすと結果を調整できます。');}catch(e){if(token===generation){stop();status('検知失敗：'+e.message,true);}}finally{busy=false;controls();}}
$('camera').onclick=async()=>{stop();if(source)source.close();source=null;clear();const token=generation;try{if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia)throw Error('携帯のカメラにはHTTPSが必要です。READMEの接続方法を確認してください。');const s=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}}});if(token!==generation){s.getTracks().forEach(t=>t.stop());return;}stream=s;const v=$('video');v.srcObject=s;await v.play();controls();$('sourceLabel').textContent='LIVE CAMERA';const loop=async()=>{if(!stream||token!==generation)return;await run(v,token);if(stream&&token===generation)setTimeout(loop,80);};loop();}catch(e){stop();status('カメラを開始できません：'+e.message,true);}};
$('stop').onclick=()=>{stop();status('カメラを停止しました。');};
$('file').onchange=async e=>{const file=e.target.files[0];if(!file)return;stop();const token=generation;clear();status('画像を読み込んでいます…');try{const image=await createImageBitmap(file,{imageOrientation:'from-image'});if(token!==generation){image.close();return;}if(source)source.close();source=image;$('sourceLabel').textContent='UPLOADED IMAGE';while(busy)await new Promise(r=>setTimeout(r,30));if(token===generation)await run(source,token);}catch(e){status('画像を読み込めません。JPEG / PNG / WebP画像を選択してください。',true);}e.target.value='';};
$('model').onchange=load;$('quality').onchange=()=>{if(source)run(source,generation);};$('threshold').oninput=()=>{$('thresholdText').textContent=$('threshold').value+'%';if(!busy)paint();};$('mask').onchange=()=>{if(!busy)paint();};$('save').onclick=()=>{const a=document.createElement('a');a.download=`scratch-${model}-${Date.now()}.png`;a.href=result.toDataURL('image/png');a.click();};document.addEventListener('visibilitychange',()=>{if(document.hidden&&stream){stop();status('画面を離れたためカメラを停止しました。');}});window.addEventListener('pagehide',stop);load();
